version: '3.1'

services:

  db:
    container_name: sql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    command: mysqld --sql-mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: hjkl
    ports:
      - 3306:3306

  adminer:
    container_name: sql_db_manager
    image: adminer
    restart: always
    ports:
      - 8080:8080
